export const languages = {
    en: { name: 'English', dir: 'ltr', caseless: false },
    fr: { name: 'Français', dir: 'ltr', caseless: false },
    es: { name: 'Español', dir: 'ltr', caseless: false },
    de: { name: 'Deutsch', dir: 'ltr', caseless: false },
    pt: { name: 'Português', dir: 'ltr', caseless: false },
    ru: { name: 'Русский', dir: 'ltr', caseless: false },
    ar: { name: 'العربية', dir: 'rtl', caseless: true },
    hi: { name: 'हिन्दी', dir: 'ltr', caseless: true },
    bn: { name: 'বাংলা', dir: 'ltr', caseless: true },
    zh: { name: '中文', dir: 'ltr', caseless: true, composing: true },
    ja: { name: '日本語', dir: 'ltr', caseless: true, composing: true },
    id: { name: 'Bahasa Indonesia', dir: 'ltr', caseless: false },
    ko: { name: '한국어', dir: 'ltr', caseless: true },
    tr: { name: 'Türkçe', dir: 'ltr', caseless: false },
    fa: { name: 'فارسی', dir: 'rtl', caseless: true },
    ur: { name: 'اردو', dir: 'rtl', caseless: true },
    vi: { name: 'Tiếng Việt', dir: 'ltr', caseless: false },
    it: { name: 'Italiano', dir: 'ltr', caseless: false },
    pl: { name: 'Polski', dir: 'ltr', caseless: false },
    uk: { name: 'Українська', dir: 'ltr', caseless: false },
    nl: { name: 'Nederlands', dir: 'ltr', caseless: false },
    el: { name: 'Ελληνικά', dir: 'ltr', caseless: false },
    he: { name: 'עברית', dir: 'rtl', caseless: true },
    tl: { name: 'Tagalog', dir: 'ltr', caseless: false },
    sw: { name: 'Kiswahili', dir: 'ltr', caseless: false },
    ha: { name: 'Hausa', dir: 'ltr', caseless: false },
};
